version: '3'
services:
  mongo:
    build: mongo/.
    image: my-mongo:1.0
    container_name: my-mongodb
    ports:
      - "27017:27017"
  mysql:
    image: mysql:5.6
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/setting:/etc/mysql/conf.d
      - ./mysql/initialize:/docker-entrypoint-initdb.d
